name: On push main
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  
  update-version:
    uses: RF-SMART-for-OracleCloud/phoenix-reusable-workflows/.github/workflows/update-version.yaml@main
    permissions:
      contents: write
    secrets: inherit

  run-build:
    if: ${{ needs.update-version.outputs.part != 'none' }}
    needs: 
      - update-version
    uses: RF-SMART-for-OracleCloud/phoenix-reusable-workflows/.github/workflows/docker-build.yaml@main
    with:
      image: ghcr.io/rf-smart-for-oraclecloud/licensing-web
      dockerfile: Rfsmart.Phoenix.Licensing.Web/Dockerfile
      version: ${{ needs.update-version.outputs.version }}
    name: Docker build
    permissions:
      contents: read
      packages: write
    secrets: inherit

  ## phxdev
  deploy-phxdev:
    needs:
      - update-version
      - run-build
    uses: RF-SMART-for-OracleCloud/phoenix-reusable-workflows/.github/workflows/terraform.yaml@main
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      aws-env: phxdev
      tf-directory: ./iac/deploys/licensing-web
      pre-deploy-script: |
        $env:TF_VAR_app_image_tag = "${{ needs.update-version.outputs.version }}"
